name: 📖 学习助手使用指南改进
description: 学习助手使用指南问题或建议改进
title: "[Docs] "
labels: []
type: "Docs"
body:
  - type: markdown
    attributes:
      value: |
        感谢你帮助改进学习助手使用指南！好的文档对用户非常重要。

  - type: input
    id: title
    attributes:
      label: 问题标题
      description: 简洁描述学习助手使用指南具体问题
      placeholder: 例如：Obsidian使用指南中的白板使用方式修改建议
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 问题类型
      description: 这是什么类型的文档问题？
      options:
        - 错误信息 - 文档内容有误
        - 信息缺失 - 缺少重要信息
        - 表达不清 - 说明不够清楚
        - 格式问题 - 排版或格式有问题
        - 过时内容 - 信息已经过时
        - 新增建议 - 建议添加新内容
        - 其他     - 任何可能的其他类型问题
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 文档位置
      description: 问题出现在哪个文件或页面？
      placeholder: 例如：AI学习助手完整使用文档.md 第25-30行，或AI学习助手完整使用文档的4.1.2.1节
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: 当前内容
      description: 复制有问题的现有内容（如果有）
      render: markdown

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 详细描述文档中存在什么问题
      placeholder: |
        例如：
        - 白板有哪些可以使用的工具
        - 白板中支持哪些类型的文件
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: 改进建议
      description: 你建议如何修改或改进？
      placeholder: |
        例如：
        在4.1.2.1中添加：
        "白板支持pdf、笔记、媒体文件（包括视频和音频），并且可以添加额外说明的功能卡片、组、幻灯片"
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 参考资料
      description: 有没有相关的资料或其他项目的好例子？
      placeholder: |
        例如：
        - 某某项目的文档写得很清楚
        - 相关的官方文档链接
        - 有用的教程或博客文章

  - type: checkboxes
    id: terms
    attributes:
      label: 确认项目
      options:
        - label: 我已经阅读了相关的现有文档
          required: true
        - label: 我已经搜索过是否有类似的文档改进建议
          required: true
        - label: 我的建议有助于改善用户体验
          required: true
